apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.s3.aws.upbound.io
spec:
  group: s3.aws.upbound.io
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                forProvider:
                  type: object
                  properties:
                    bucketName:
                      type: string
                    acl:
                      type: string
                    versioning:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                  required:
                    - bucketName
                    - acl
                    - versioning
              required:
                - forProvider
            
  connectionSecretKeys:
    - bucketName
    - bucketArn
