apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-git
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hellenavilarosa/crossplane.git
    targetRevision: HEAD
    path: App/Application/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    prune: true
    automated:
      prune: true
      selfHeal: true


